ingress:
  name: ingress-mern-service
  namespace: mern-ns
  enabled: true
  ingressClassName: nginx
  rules:
    - path: "/"
      pathType: Prefix
      backend:
        service:
          name: client-service
          port:
            number: 80
    - path: "/api"
      pathType: Prefix
      backend:
        service:
          name: backend-service
          port:
            number: 5000