apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
  namespace: mern-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app/component: backend-api
  template:
    metadata:
      labels:
        app/name: mern-app
        app/component: backend-api
    spec:
      containers:
      - name: backendcontainer
        image: m0dd/k8s-backend-demo
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: mongodb-cred
        env:
        - name: MONGOURI
          value: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-service:27017/m0ddb?authSource=admin"
        ports:
        - containerPort: 5000
