apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mern-service
  namespace: mern-ns
spec:
  rules:
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: client-service
            port: 
              number: 80
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: backend-service
            port: 
              number: 5000

