apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.ingress.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - http:
        paths:
{{- range .Values.ingress.rules }}
          - pathType: Prefix
            path: {{ .path | quote }}
            backend:
              service:
                name: {{ .backend.service.name }}
                port:
                  number: {{ .backend.service.port.number }}
{{- end }}