name: mern-backend
namespace: mern-ns
replicaCount: 2
podLabels:
  name: mern-app
  component: backend-api
container:
  image: m0dd/k8s-backend-demo
  port: 5000
  MONGOURI: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-headless:27017/m0ddb?authSource=admin"
secret:
  name: mongodb-cred